name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  gulp:
    name: Build gulp file
    runs-on: ubuntu-latest
    steps:
     - name: Clone repo
       uses: actions/checkout@v3

     - name: Run gulp file
       run: echo "Hello world"
