name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  gulp:
    name: Build gulp file
    runs-on: self-hosted
    steps:
     - name: Clone repo
       uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
         node-version: 16
         cache: 'npm'

     - name: Run gulp file
       run: | 
         npm ci
         cd theme/
         npm run build
